manifest:
  remotes:
    - name: zephyr
      url-base: https://github.com/zephyrproject-rtos
    - name: thedjnK
      url-base: https://github.com/thedjnK

  projects:
    - name: zephyr
      remote: zephyr
      revision: pull/75197/head
      import:
        name-allowlist:
          - cmsis
          - hal_nordic
          - loramac-node
          - mcuboot
          - picolibc
          - tinycrypt
          - zcbor
    - name: boards
      remote: thedjnK
      revision: main

  self:
    path: lora-hacks
