CONFIG_PICOLIBC_USE_MODULE=y
# CONFIG_PICOLIBC_USE_TOOLCHAIN is not set
# CONFIG_PICOLIBC_IO_LONG_LONG is not set
# CONFIG_PICOLIBC_IO_INTEGER is not set
CONFIG_PICOLIBC_IO_MINIMAL=y
# CONFIG_PICOLIBC_SIZE_OPTIMIZATIONS is not set
CONFIG_PICOLIBC_SPEED_OPTIMIZATIONS=y
# CONFIG_PICOLIBC_DEBUG_OPTIMIZATIONS is not set
# CONFIG_PICOLIBC_NO_OPTIMIZATIONS is not set
CONFIG_PICOLIBC_FAST_STRCMP=y
# CONFIG_PICOLIBC_ASSERT_VERBOSE is not set
# CONFIG_PICOLIBC_IO_C99_FORMATS is not set
# CONFIG_PICOLIBC_IO_FLOAT_EXACT is not set
CONFIG_PICOLIBC_IO_SMALL_ULTOA=y
# CONFIG_PICOLIBC_IO_MINIMAL_LONG_LONG is not set
# CONFIG_PICOLIBC_LOCALE_INFO is not set
# CONFIG_PICOLIBC_LOCALE_EXTENDED_INFO is not set
# CONFIG_PICOLIBC_MULTIBYTE is not set
CONFIG_PICOLIBC_PICOEXIT=y
CONFIG_PICOLIBC_MULTITHREAD=y
# CONFIG_PICOLIBC_GLOBAL_ERRNO is not set
# CONFIG_CBPRINTF_COMPLETE is not set
CONFIG_CBPRINTF_NANO=y
CONFIG_CBPRINTF_REDUCED_INTEGRAL=y
CONFIG_BT_CTLR_OPTIMIZE_FOR_SPEED=y
CONFIG_COMPILER_OPT="-O2 -fno-math-errno -fno-trapping-math -ffast-math -fallow-store-data-races"
